name: Generate geosite-list.md

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 0 * * *"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Clone Repositories
      run: |
        git clone --depth 1 https://github.com/v2fly/domain-list-community.git data/domain-list-community
        git clone --depth 1 https://github.com/Orz-3/mini.git data/orz-3-mini

    - name: Generate Resources
      run: |
        python scripts/main.py

    - uses: EndBug/add-and-commit@v9
      with:
        add: 'geosite-list.md icons/'
        author_name: Edward Chen
        author_email: hi@edch.top
        message: 'Update geosite-list.md and icons'